import { StyleSheet, Dimensions } from 'react-native';
import Theme from '../../styles/theme';

const { width } = Dimensions.get('window');
const CARD_W = (width - 40 - 16) / 2;

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  header: {
    height: 64,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.colors.border,
  },
  menu: { fontSize: 16, color: Theme.colors.primary, fontWeight: '700' },
  title: { fontSize: 18, fontWeight: '700', color: Theme.colors.text },
  support: { color: Theme.colors.primary, fontWeight: '700' },
  content: { padding: 20 },
  hi: { fontSize: 24, fontWeight: '700', marginBottom: 6, color: Theme.colors.text },
  subtitle: { color: Theme.colors.textSecondary, marginBottom: 24, fontSize: 15 },
  buttonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  card: {
    width: CARD_W,
    height: CARD_W * 1.2,
    borderRadius: 20,
    backgroundColor: Theme.colors.surface,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  imagePlaceholder: {
    flex: 1,
    backgroundColor: Theme.colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: {
    color: Theme.colors.primary,
    fontWeight: '700',
    fontSize: 16,
  },
  cardLabel: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.text,
  },
  cardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  actionCard: {
    width: CARD_W,
    backgroundColor: Theme.colors.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  cardIcon: {
    fontSize: 20,
  },
  cardTitle: {
    fontFamily: Theme.typography.fontFamily,
    fontSize: 16,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  cardSub: {
    fontFamily: Theme.typography.fontFamily,
    fontSize: 12,
    color: Theme.colors.textSecondary,
    marginTop: 4,
  },
  footerBox: {
    marginTop: 32,
    padding: 24,
    borderRadius: 20,
    backgroundColor: Theme.colors.surface,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
  },
  footerTitle: {
    fontFamily: Theme.typography.fontFamily,
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.text,
    marginBottom: 8,
  },
  footerText: {
    fontFamily: Theme.typography.fontFamily,
    fontSize: 14,
    color: Theme.colors.textSecondary,
    lineHeight: 20,
    textAlign: 'center',
  },
  ghostBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.surface,
  },
  ghostBtnText: {
    fontFamily: Theme.typography.fontFamily,
    color: Theme.colors.textSecondary,
    fontWeight: '600',
    fontSize: 14,
  },
  sectionTitle: {
    fontFamily: Theme.typography.fontFamily,
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.text,
    marginBottom: 4,
  },
  fab: {
    position: 'absolute',
    bottom: 0,
    right: 20,
    backgroundColor: Theme.colors.primary,
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  fabBadge: {
    position: 'absolute',
    top: -2,
    left: -2,
    backgroundColor: Theme.colors.onPrimary,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    zIndex: 1,
    borderWidth: 2,
    borderColor: Theme.colors.primary,
  },
  fabBadgeText: {
    color: Theme.colors.primary,
    fontSize: 10,
    fontWeight: '900',
  },
});
