import { StyleSheet } from 'react-native';
import Theme from '../../styles/theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  header: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: Theme.colors.border,
  },
  backBtn: { padding: 8 },
  title: { fontSize: 18, fontWeight: '700', color: Theme.colors.text },
  content: { padding: 24 },
  profileSection: { alignItems: 'center', marginBottom: 40 },
  statusSection: { alignItems: 'center', marginBottom: 32 },
  badge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 },
  freeBadge: { backgroundColor: Theme.colors.surfaceContainer },
  freeBadgeText: { fontSize: 10, fontWeight: '800', color: Theme.colors.textMuted },
  premiumBadge: { backgroundColor: 'rgba(255, 179, 180, 0.2)' },
  premiumBadgeText: { fontSize: 10, fontWeight: '800', color: Theme.colors.primary },
  section: { marginBottom: 32 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
    marginLeft: 4,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Theme.colors.surface,
    padding: 16,
    borderRadius: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  menuItemLeft: { flexDirection: 'row', alignItems: 'center' },
  menuItemText: { fontSize: 16, fontWeight: '600', color: Theme.colors.text, marginLeft: 12 },
  versionText: { fontSize: 14, color: Theme.colors.textMuted },
  copyright: {
    textAlign: 'center',
    fontSize: 12,
    color: Theme.colors.textMuted,
    marginTop: 20,
    marginBottom: 40,
  },
});
